/** * Catch and report unexpected error. * @param {any} error The thrown error object. * @returns {void} */function onFatalError(error) {    process.exitCode = 2;    const { version } = require("./package.json");    console.error(`Oops! Something went wrong! :(MyTool: ${version}${error}`);}//------------------------------------------------------------------------------// Execution//------------------------------------------------------------------------------(async function main() {    process.on("uncaughtException", onFatalError);    process.on("unhandledRejection", onFatalError);    process.exitCode = await require("./cli").execute(process.argv);}()).catch(onFatalError);